blank_issues_enabled: false
contact_links:
  - name: ğŸ“– Documentation
    url: https://github.com/McIntosh-Lab/tvb-ukbb/wiki
    about: Official tvb-ukbb documentation
  - name: â“ FAQ
    about: Frequently Asked Questions
    url: https://github.com/McIntosh-Lab/tvb-ukbb/wiki/FAQ
  - name: ğŸ’¬ Questions & Discussion
    about: Discussions Board
    url: https://github.com/McIntosh-Lab/tvb-ukbb/discussions
  - name: ğŸ’¡ Feature Requests
    url: https://github.com/McIntosh-Lab/tvb-ukbb/discussions/new/choose
    about: tvb-ukbb missing something? Let us know.
