blank_issues_enabled: false
contact_links:
  - name: ğŸ“– Documentation
    url: https://github.com/McIntosh-Lab/tvb-ukbb/wiki
    about: Official tvb-ukbb documentation
  - name: â“ FAQ
    url: https://github.com/McIntosh-Lab/tvb-ukbb/wiki/FAQ
    about: Frequently Asked Questions
  - name: ğŸ’¬ Questions & Discussion
    url: https://github.com/McIntosh-Lab/tvb-ukbb/discussions
    about: Discussions Board
  - name: ğŸ’¡ Feature Requests
    url: https://github.com/McIntosh-Lab/tvb-ukbb/discussions/new/choose
    about: Is tvb-ukbb missing something?
  - name: ğŸ› ï¸ Support Requests
    url: https://github.com/McIntosh-Lab/tvb-ukbb/discussions/new/choose
    about: Something not working? Having trouble with installation or processing?
